// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package agentsight

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type agentsightEvent struct {
	Type        uint32
	Pid         int32
	Ppid        int32
	ExitCode    uint32
	DurationNs  uint64
	TimestampNs uint64
	Comm        [16]int8
	FullCommand [256]int8
	Filename    [127]int8
	_           [129]byte
	ExitEvent   bool
	_           [7]byte
}

type agentsightIoArgsT struct {
	Buf     uint64
	StartNs uint64
	Fd      int32
	IsRead  uint8
	_       [3]byte
}

type agentsightProbeSSL_dataT struct {
	TimestampNs uint64
	DeltaNs     uint64
	Pid         uint32
	Tid         uint32
	Uid         uint32
	Len         uint32
	BufSize     uint32
	BufFilled   int32
	Rw          int32
	Comm        [16]int8
	Buf         [524288]uint8
	IsHandshake int32
}

type agentsightStdiocapEventT struct {
	TimestampNs uint64
	DeltaNs     uint64
	Pid         uint32
	Tid         uint32
	Uid         uint32
	Fd          int32
	Len         uint32
	BufSize     uint32
	IsRead      uint8
	Comm        [16]int8
	Buf         [8192]uint8
	_           [7]byte
}

// loadAgentsight returns the embedded CollectionSpec for agentsight.
func loadAgentsight() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AgentsightBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load agentsight: %w", err)
	}

	return spec, err
}

// loadAgentsightObjects loads agentsight and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*agentsightObjects
//	*agentsightPrograms
//	*agentsightMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAgentsightObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAgentsight()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// agentsightSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type agentsightSpecs struct {
	agentsightProgramSpecs
	agentsightMapSpecs
	agentsightVariableSpecs
}

// agentsightProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type agentsightProgramSpecs struct {
	BashReadline              *ebpf.ProgramSpec `ebpf:"bash_readline"`
	HandleExec                *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleExit                *ebpf.ProgramSpec `ebpf:"handle_exit"`
	ProbeSSL_doHandshakeEnter *ebpf.ProgramSpec `ebpf:"probe_SSL_do_handshake_enter"`
	ProbeSSL_doHandshakeExit  *ebpf.ProgramSpec `ebpf:"probe_SSL_do_handshake_exit"`
	ProbeSSL_readExEnter      *ebpf.ProgramSpec `ebpf:"probe_SSL_read_ex_enter"`
	ProbeSSL_readExExit       *ebpf.ProgramSpec `ebpf:"probe_SSL_read_ex_exit"`
	ProbeSSL_readExit         *ebpf.ProgramSpec `ebpf:"probe_SSL_read_exit"`
	ProbeSSL_rwEnter          *ebpf.ProgramSpec `ebpf:"probe_SSL_rw_enter"`
	ProbeSSL_writeExEnter     *ebpf.ProgramSpec `ebpf:"probe_SSL_write_ex_enter"`
	ProbeSSL_writeExExit      *ebpf.ProgramSpec `ebpf:"probe_SSL_write_ex_exit"`
	ProbeSSL_writeExit        *ebpf.ProgramSpec `ebpf:"probe_SSL_write_exit"`
	TraceCommitCreds          *ebpf.ProgramSpec `ebpf:"trace_commit_creds"`
	TraceConnect              *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceEnterRead            *ebpf.ProgramSpec `ebpf:"trace_enter_read"`
	TraceEnterWrite           *ebpf.ProgramSpec `ebpf:"trace_enter_write"`
	TraceExitRead             *ebpf.ProgramSpec `ebpf:"trace_exit_read"`
	TraceExitWrite            *ebpf.ProgramSpec `ebpf:"trace_exit_write"`
	TraceMkdir                *ebpf.ProgramSpec `ebpf:"trace_mkdir"`
	TraceMkdirat              *ebpf.ProgramSpec `ebpf:"trace_mkdirat"`
	TraceOpen                 *ebpf.ProgramSpec `ebpf:"trace_open"`
	TraceOpenat               *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TraceRename               *ebpf.ProgramSpec `ebpf:"trace_rename"`
	TraceRenameat             *ebpf.ProgramSpec `ebpf:"trace_renameat"`
	TraceRenameat2            *ebpf.ProgramSpec `ebpf:"trace_renameat2"`
	TraceUnlink               *ebpf.ProgramSpec `ebpf:"trace_unlink"`
	TraceUnlinkat             *ebpf.ProgramSpec `ebpf:"trace_unlinkat"`
}

// agentsightMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type agentsightMapSpecs struct {
	Bufs          *ebpf.MapSpec `ebpf:"bufs"`
	ExecStart     *ebpf.MapSpec `ebpf:"exec_start"`
	IoArgs        *ebpf.MapSpec `ebpf:"io_args"`
	RbProcess     *ebpf.MapSpec `ebpf:"rb_process"`
	RbSsl         *ebpf.MapSpec `ebpf:"rb_ssl"`
	RbStdio       *ebpf.MapSpec `ebpf:"rb_stdio"`
	ReadbytesPtrs *ebpf.MapSpec `ebpf:"readbytes_ptrs"`
	StartNs       *ebpf.MapSpec `ebpf:"start_ns"`
}

// agentsightVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type agentsightVariableSpecs struct {
	MaxCaptureBytes     *ebpf.VariableSpec `ebpf:"max_capture_bytes"`
	MinDurationNs       *ebpf.VariableSpec `ebpf:"min_duration_ns"`
	SslTargPid          *ebpf.VariableSpec `ebpf:"ssl_targ_pid"`
	SslTargUid          *ebpf.VariableSpec `ebpf:"ssl_targ_uid"`
	StdioTargPid        *ebpf.VariableSpec `ebpf:"stdio_targ_pid"`
	StdioTargUid        *ebpf.VariableSpec `ebpf:"stdio_targ_uid"`
	TraceStdioOnly      *ebpf.VariableSpec `ebpf:"trace_stdio_only"`
	UnusedEvent         *ebpf.VariableSpec `ebpf:"unused_event"`
	UnusedSslData       *ebpf.VariableSpec `ebpf:"unused_ssl_data"`
	UnusedStdiocapEvent *ebpf.VariableSpec `ebpf:"unused_stdiocap_event"`
}

// agentsightObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAgentsightObjects or ebpf.CollectionSpec.LoadAndAssign.
type agentsightObjects struct {
	agentsightPrograms
	agentsightMaps
	agentsightVariables
}

func (o *agentsightObjects) Close() error {
	return _AgentsightClose(
		&o.agentsightPrograms,
		&o.agentsightMaps,
	)
}

// agentsightMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAgentsightObjects or ebpf.CollectionSpec.LoadAndAssign.
type agentsightMaps struct {
	Bufs          *ebpf.Map `ebpf:"bufs"`
	ExecStart     *ebpf.Map `ebpf:"exec_start"`
	IoArgs        *ebpf.Map `ebpf:"io_args"`
	RbProcess     *ebpf.Map `ebpf:"rb_process"`
	RbSsl         *ebpf.Map `ebpf:"rb_ssl"`
	RbStdio       *ebpf.Map `ebpf:"rb_stdio"`
	ReadbytesPtrs *ebpf.Map `ebpf:"readbytes_ptrs"`
	StartNs       *ebpf.Map `ebpf:"start_ns"`
}

func (m *agentsightMaps) Close() error {
	return _AgentsightClose(
		m.Bufs,
		m.ExecStart,
		m.IoArgs,
		m.RbProcess,
		m.RbSsl,
		m.RbStdio,
		m.ReadbytesPtrs,
		m.StartNs,
	)
}

// agentsightVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAgentsightObjects or ebpf.CollectionSpec.LoadAndAssign.
type agentsightVariables struct {
	MaxCaptureBytes     *ebpf.Variable `ebpf:"max_capture_bytes"`
	MinDurationNs       *ebpf.Variable `ebpf:"min_duration_ns"`
	SslTargPid          *ebpf.Variable `ebpf:"ssl_targ_pid"`
	SslTargUid          *ebpf.Variable `ebpf:"ssl_targ_uid"`
	StdioTargPid        *ebpf.Variable `ebpf:"stdio_targ_pid"`
	StdioTargUid        *ebpf.Variable `ebpf:"stdio_targ_uid"`
	TraceStdioOnly      *ebpf.Variable `ebpf:"trace_stdio_only"`
	UnusedEvent         *ebpf.Variable `ebpf:"unused_event"`
	UnusedSslData       *ebpf.Variable `ebpf:"unused_ssl_data"`
	UnusedStdiocapEvent *ebpf.Variable `ebpf:"unused_stdiocap_event"`
}

// agentsightPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAgentsightObjects or ebpf.CollectionSpec.LoadAndAssign.
type agentsightPrograms struct {
	BashReadline              *ebpf.Program `ebpf:"bash_readline"`
	HandleExec                *ebpf.Program `ebpf:"handle_exec"`
	HandleExit                *ebpf.Program `ebpf:"handle_exit"`
	ProbeSSL_doHandshakeEnter *ebpf.Program `ebpf:"probe_SSL_do_handshake_enter"`
	ProbeSSL_doHandshakeExit  *ebpf.Program `ebpf:"probe_SSL_do_handshake_exit"`
	ProbeSSL_readExEnter      *ebpf.Program `ebpf:"probe_SSL_read_ex_enter"`
	ProbeSSL_readExExit       *ebpf.Program `ebpf:"probe_SSL_read_ex_exit"`
	ProbeSSL_readExit         *ebpf.Program `ebpf:"probe_SSL_read_exit"`
	ProbeSSL_rwEnter          *ebpf.Program `ebpf:"probe_SSL_rw_enter"`
	ProbeSSL_writeExEnter     *ebpf.Program `ebpf:"probe_SSL_write_ex_enter"`
	ProbeSSL_writeExExit      *ebpf.Program `ebpf:"probe_SSL_write_ex_exit"`
	ProbeSSL_writeExit        *ebpf.Program `ebpf:"probe_SSL_write_exit"`
	TraceCommitCreds          *ebpf.Program `ebpf:"trace_commit_creds"`
	TraceConnect              *ebpf.Program `ebpf:"trace_connect"`
	TraceEnterRead            *ebpf.Program `ebpf:"trace_enter_read"`
	TraceEnterWrite           *ebpf.Program `ebpf:"trace_enter_write"`
	TraceExitRead             *ebpf.Program `ebpf:"trace_exit_read"`
	TraceExitWrite            *ebpf.Program `ebpf:"trace_exit_write"`
	TraceMkdir                *ebpf.Program `ebpf:"trace_mkdir"`
	TraceMkdirat              *ebpf.Program `ebpf:"trace_mkdirat"`
	TraceOpen                 *ebpf.Program `ebpf:"trace_open"`
	TraceOpenat               *ebpf.Program `ebpf:"trace_openat"`
	TraceRename               *ebpf.Program `ebpf:"trace_rename"`
	TraceRenameat             *ebpf.Program `ebpf:"trace_renameat"`
	TraceRenameat2            *ebpf.Program `ebpf:"trace_renameat2"`
	TraceUnlink               *ebpf.Program `ebpf:"trace_unlink"`
	TraceUnlinkat             *ebpf.Program `ebpf:"trace_unlinkat"`
}

func (p *agentsightPrograms) Close() error {
	return _AgentsightClose(
		p.BashReadline,
		p.HandleExec,
		p.HandleExit,
		p.ProbeSSL_doHandshakeEnter,
		p.ProbeSSL_doHandshakeExit,
		p.ProbeSSL_readExEnter,
		p.ProbeSSL_readExExit,
		p.ProbeSSL_readExit,
		p.ProbeSSL_rwEnter,
		p.ProbeSSL_writeExEnter,
		p.ProbeSSL_writeExExit,
		p.ProbeSSL_writeExit,
		p.TraceCommitCreds,
		p.TraceConnect,
		p.TraceEnterRead,
		p.TraceEnterWrite,
		p.TraceExitRead,
		p.TraceExitWrite,
		p.TraceMkdir,
		p.TraceMkdirat,
		p.TraceOpen,
		p.TraceOpenat,
		p.TraceRename,
		p.TraceRenameat,
		p.TraceRenameat2,
		p.TraceUnlink,
		p.TraceUnlinkat,
	)
}

func _AgentsightClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed agentsight_x86_bpfel.o
var _AgentsightBytes []byte
