// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package stdiocap

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type stdiocapIoArgsT struct {
	Buf     uint64
	StartNs uint64
	Fd      int32
	IsRead  uint8
	_       [3]byte
}

type stdiocapStdiocapEventT struct {
	TimestampNs uint64
	DeltaNs     uint64
	Pid         uint32
	Tid         uint32
	Uid         uint32
	Fd          int32
	Len         uint32
	BufSize     uint32
	IsRead      uint8
	Comm        [16]int8
	Buf         [8192]uint8
	_           [7]byte
}

// loadStdiocap returns the embedded CollectionSpec for stdiocap.
func loadStdiocap() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_StdiocapBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load stdiocap: %w", err)
	}

	return spec, err
}

// loadStdiocapObjects loads stdiocap and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*stdiocapObjects
//	*stdiocapPrograms
//	*stdiocapMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadStdiocapObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadStdiocap()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// stdiocapSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stdiocapSpecs struct {
	stdiocapProgramSpecs
	stdiocapMapSpecs
	stdiocapVariableSpecs
}

// stdiocapProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stdiocapProgramSpecs struct {
	TraceEnterRead  *ebpf.ProgramSpec `ebpf:"trace_enter_read"`
	TraceEnterWrite *ebpf.ProgramSpec `ebpf:"trace_enter_write"`
	TraceExitRead   *ebpf.ProgramSpec `ebpf:"trace_exit_read"`
	TraceExitWrite  *ebpf.ProgramSpec `ebpf:"trace_exit_write"`
}

// stdiocapMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stdiocapMapSpecs struct {
	IoArgs *ebpf.MapSpec `ebpf:"io_args"`
	Rb     *ebpf.MapSpec `ebpf:"rb"`
}

// stdiocapVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stdiocapVariableSpecs struct {
	MaxCaptureBytes     *ebpf.VariableSpec `ebpf:"max_capture_bytes"`
	TargPid             *ebpf.VariableSpec `ebpf:"targ_pid"`
	TargUid             *ebpf.VariableSpec `ebpf:"targ_uid"`
	TraceStdioOnly      *ebpf.VariableSpec `ebpf:"trace_stdio_only"`
	UnusedStdiocapEvent *ebpf.VariableSpec `ebpf:"unused_stdiocap_event"`
}

// stdiocapObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadStdiocapObjects or ebpf.CollectionSpec.LoadAndAssign.
type stdiocapObjects struct {
	stdiocapPrograms
	stdiocapMaps
	stdiocapVariables
}

func (o *stdiocapObjects) Close() error {
	return _StdiocapClose(
		&o.stdiocapPrograms,
		&o.stdiocapMaps,
	)
}

// stdiocapMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadStdiocapObjects or ebpf.CollectionSpec.LoadAndAssign.
type stdiocapMaps struct {
	IoArgs *ebpf.Map `ebpf:"io_args"`
	Rb     *ebpf.Map `ebpf:"rb"`
}

func (m *stdiocapMaps) Close() error {
	return _StdiocapClose(
		m.IoArgs,
		m.Rb,
	)
}

// stdiocapVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadStdiocapObjects or ebpf.CollectionSpec.LoadAndAssign.
type stdiocapVariables struct {
	MaxCaptureBytes     *ebpf.Variable `ebpf:"max_capture_bytes"`
	TargPid             *ebpf.Variable `ebpf:"targ_pid"`
	TargUid             *ebpf.Variable `ebpf:"targ_uid"`
	TraceStdioOnly      *ebpf.Variable `ebpf:"trace_stdio_only"`
	UnusedStdiocapEvent *ebpf.Variable `ebpf:"unused_stdiocap_event"`
}

// stdiocapPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadStdiocapObjects or ebpf.CollectionSpec.LoadAndAssign.
type stdiocapPrograms struct {
	TraceEnterRead  *ebpf.Program `ebpf:"trace_enter_read"`
	TraceEnterWrite *ebpf.Program `ebpf:"trace_enter_write"`
	TraceExitRead   *ebpf.Program `ebpf:"trace_exit_read"`
	TraceExitWrite  *ebpf.Program `ebpf:"trace_exit_write"`
}

func (p *stdiocapPrograms) Close() error {
	return _StdiocapClose(
		p.TraceEnterRead,
		p.TraceEnterWrite,
		p.TraceExitRead,
		p.TraceExitWrite,
	)
}

func _StdiocapClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed stdiocap_x86_bpfel.o
var _StdiocapBytes []byte
