// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package process

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type processEvent struct {
	Type        uint32
	Pid         int32
	Ppid        int32
	ExitCode    uint32
	DurationNs  uint64
	TimestampNs uint64
	Comm        [16]int8
	FullCommand [256]int8
	Filename    [127]int8
	_           [129]byte
	ExitEvent   bool
	_           [7]byte
}

// loadProcess returns the embedded CollectionSpec for process.
func loadProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load process: %w", err)
	}

	return spec, err
}

// loadProcessObjects loads process and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processObjects
//	*processPrograms
//	*processMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processSpecs struct {
	processProgramSpecs
	processMapSpecs
	processVariableSpecs
}

// processProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processProgramSpecs struct {
	BashReadline     *ebpf.ProgramSpec `ebpf:"bash_readline"`
	HandleExec       *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleExit       *ebpf.ProgramSpec `ebpf:"handle_exit"`
	TraceCommitCreds *ebpf.ProgramSpec `ebpf:"trace_commit_creds"`
	TraceConnect     *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceMkdir       *ebpf.ProgramSpec `ebpf:"trace_mkdir"`
	TraceMkdirat     *ebpf.ProgramSpec `ebpf:"trace_mkdirat"`
	TraceOpen        *ebpf.ProgramSpec `ebpf:"trace_open"`
	TraceOpenat      *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TraceRename      *ebpf.ProgramSpec `ebpf:"trace_rename"`
	TraceRenameat    *ebpf.ProgramSpec `ebpf:"trace_renameat"`
	TraceRenameat2   *ebpf.ProgramSpec `ebpf:"trace_renameat2"`
	TraceUnlink      *ebpf.ProgramSpec `ebpf:"trace_unlink"`
	TraceUnlinkat    *ebpf.ProgramSpec `ebpf:"trace_unlinkat"`
}

// processMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMapSpecs struct {
	ExecStart *ebpf.MapSpec `ebpf:"exec_start"`
	Rb        *ebpf.MapSpec `ebpf:"rb"`
}

// processVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processVariableSpecs struct {
	MinDurationNs *ebpf.VariableSpec `ebpf:"min_duration_ns"`
	UnusedEvent   *ebpf.VariableSpec `ebpf:"unused_event"`
}

// processObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processObjects struct {
	processPrograms
	processMaps
	processVariables
}

func (o *processObjects) Close() error {
	return _ProcessClose(
		&o.processPrograms,
		&o.processMaps,
	)
}

// processMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMaps struct {
	ExecStart *ebpf.Map `ebpf:"exec_start"`
	Rb        *ebpf.Map `ebpf:"rb"`
}

func (m *processMaps) Close() error {
	return _ProcessClose(
		m.ExecStart,
		m.Rb,
	)
}

// processVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processVariables struct {
	MinDurationNs *ebpf.Variable `ebpf:"min_duration_ns"`
	UnusedEvent   *ebpf.Variable `ebpf:"unused_event"`
}

// processPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processPrograms struct {
	BashReadline     *ebpf.Program `ebpf:"bash_readline"`
	HandleExec       *ebpf.Program `ebpf:"handle_exec"`
	HandleExit       *ebpf.Program `ebpf:"handle_exit"`
	TraceCommitCreds *ebpf.Program `ebpf:"trace_commit_creds"`
	TraceConnect     *ebpf.Program `ebpf:"trace_connect"`
	TraceMkdir       *ebpf.Program `ebpf:"trace_mkdir"`
	TraceMkdirat     *ebpf.Program `ebpf:"trace_mkdirat"`
	TraceOpen        *ebpf.Program `ebpf:"trace_open"`
	TraceOpenat      *ebpf.Program `ebpf:"trace_openat"`
	TraceRename      *ebpf.Program `ebpf:"trace_rename"`
	TraceRenameat    *ebpf.Program `ebpf:"trace_renameat"`
	TraceRenameat2   *ebpf.Program `ebpf:"trace_renameat2"`
	TraceUnlink      *ebpf.Program `ebpf:"trace_unlink"`
	TraceUnlinkat    *ebpf.Program `ebpf:"trace_unlinkat"`
}

func (p *processPrograms) Close() error {
	return _ProcessClose(
		p.BashReadline,
		p.HandleExec,
		p.HandleExit,
		p.TraceCommitCreds,
		p.TraceConnect,
		p.TraceMkdir,
		p.TraceMkdirat,
		p.TraceOpen,
		p.TraceOpenat,
		p.TraceRename,
		p.TraceRenameat,
		p.TraceRenameat2,
		p.TraceUnlink,
		p.TraceUnlinkat,
	)
}

func _ProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_x86_bpfel.o
var _ProcessBytes []byte
