// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package sslsniff

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type sslsniffProbeSSL_dataT struct {
	TimestampNs uint64
	DeltaNs     uint64
	Pid         uint32
	Tid         uint32
	Uid         uint32
	Len         uint32
	BufSize     uint32
	BufFilled   int32
	Rw          int32
	Comm        [16]int8
	Buf         [524288]uint8
	IsHandshake int32
}

// loadSslsniff returns the embedded CollectionSpec for sslsniff.
func loadSslsniff() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SslsniffBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sslsniff: %w", err)
	}

	return spec, err
}

// loadSslsniffObjects loads sslsniff and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sslsniffObjects
//	*sslsniffPrograms
//	*sslsniffMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSslsniffObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSslsniff()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sslsniffSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslsniffSpecs struct {
	sslsniffProgramSpecs
	sslsniffMapSpecs
	sslsniffVariableSpecs
}

// sslsniffProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslsniffProgramSpecs struct {
	ProbeSSL_doHandshakeEnter *ebpf.ProgramSpec `ebpf:"probe_SSL_do_handshake_enter"`
	ProbeSSL_doHandshakeExit  *ebpf.ProgramSpec `ebpf:"probe_SSL_do_handshake_exit"`
	ProbeSSL_readExEnter      *ebpf.ProgramSpec `ebpf:"probe_SSL_read_ex_enter"`
	ProbeSSL_readExExit       *ebpf.ProgramSpec `ebpf:"probe_SSL_read_ex_exit"`
	ProbeSSL_readExit         *ebpf.ProgramSpec `ebpf:"probe_SSL_read_exit"`
	ProbeSSL_rwEnter          *ebpf.ProgramSpec `ebpf:"probe_SSL_rw_enter"`
	ProbeSSL_writeExEnter     *ebpf.ProgramSpec `ebpf:"probe_SSL_write_ex_enter"`
	ProbeSSL_writeExExit      *ebpf.ProgramSpec `ebpf:"probe_SSL_write_ex_exit"`
	ProbeSSL_writeExit        *ebpf.ProgramSpec `ebpf:"probe_SSL_write_exit"`
}

// sslsniffMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslsniffMapSpecs struct {
	Bufs          *ebpf.MapSpec `ebpf:"bufs"`
	Rb            *ebpf.MapSpec `ebpf:"rb"`
	ReadbytesPtrs *ebpf.MapSpec `ebpf:"readbytes_ptrs"`
	StartNs       *ebpf.MapSpec `ebpf:"start_ns"`
}

// sslsniffVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslsniffVariableSpecs struct {
	TargPid       *ebpf.VariableSpec `ebpf:"targ_pid"`
	TargUid       *ebpf.VariableSpec `ebpf:"targ_uid"`
	UnusedSslData *ebpf.VariableSpec `ebpf:"unused_ssl_data"`
}

// sslsniffObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSslsniffObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslsniffObjects struct {
	sslsniffPrograms
	sslsniffMaps
	sslsniffVariables
}

func (o *sslsniffObjects) Close() error {
	return _SslsniffClose(
		&o.sslsniffPrograms,
		&o.sslsniffMaps,
	)
}

// sslsniffMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSslsniffObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslsniffMaps struct {
	Bufs          *ebpf.Map `ebpf:"bufs"`
	Rb            *ebpf.Map `ebpf:"rb"`
	ReadbytesPtrs *ebpf.Map `ebpf:"readbytes_ptrs"`
	StartNs       *ebpf.Map `ebpf:"start_ns"`
}

func (m *sslsniffMaps) Close() error {
	return _SslsniffClose(
		m.Bufs,
		m.Rb,
		m.ReadbytesPtrs,
		m.StartNs,
	)
}

// sslsniffVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSslsniffObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslsniffVariables struct {
	TargPid       *ebpf.Variable `ebpf:"targ_pid"`
	TargUid       *ebpf.Variable `ebpf:"targ_uid"`
	UnusedSslData *ebpf.Variable `ebpf:"unused_ssl_data"`
}

// sslsniffPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSslsniffObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslsniffPrograms struct {
	ProbeSSL_doHandshakeEnter *ebpf.Program `ebpf:"probe_SSL_do_handshake_enter"`
	ProbeSSL_doHandshakeExit  *ebpf.Program `ebpf:"probe_SSL_do_handshake_exit"`
	ProbeSSL_readExEnter      *ebpf.Program `ebpf:"probe_SSL_read_ex_enter"`
	ProbeSSL_readExExit       *ebpf.Program `ebpf:"probe_SSL_read_ex_exit"`
	ProbeSSL_readExit         *ebpf.Program `ebpf:"probe_SSL_read_exit"`
	ProbeSSL_rwEnter          *ebpf.Program `ebpf:"probe_SSL_rw_enter"`
	ProbeSSL_writeExEnter     *ebpf.Program `ebpf:"probe_SSL_write_ex_enter"`
	ProbeSSL_writeExExit      *ebpf.Program `ebpf:"probe_SSL_write_ex_exit"`
	ProbeSSL_writeExit        *ebpf.Program `ebpf:"probe_SSL_write_exit"`
}

func (p *sslsniffPrograms) Close() error {
	return _SslsniffClose(
		p.ProbeSSL_doHandshakeEnter,
		p.ProbeSSL_doHandshakeExit,
		p.ProbeSSL_readExEnter,
		p.ProbeSSL_readExExit,
		p.ProbeSSL_readExit,
		p.ProbeSSL_rwEnter,
		p.ProbeSSL_writeExEnter,
		p.ProbeSSL_writeExExit,
		p.ProbeSSL_writeExit,
	)
}

func _SslsniffClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sslsniff_x86_bpfel.o
var _SslsniffBytes []byte
